name: Format Translation

permissions:
  contents: write

on:
  workflow_dispatch:
  push:
    branches:
      - newartwork
    paths:
      - 'Screens/MiniGame/KinkyDungeon/*'
  pull_request:
    branches:
      - newartwork
    paths:
      - 'Screens/MiniGame/KinkyDungeon/*'
 
jobs:
  format-translation:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
            fetch-depth: 2

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'
          
      - name: üöÄ Run format-translation script
        run: python .github/scripts/format-translation-script.py Screens/MiniGame/KinkyDungeon/Text_KinkyDungeon.csv
  
      - name: üìù Commit changes 
        id: check_changes 
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "format-translation-action"
          git add . 
          git diff-index --quiet HEAD || git commit -m "Format translation files"
          git push